name: EasyStreetQuartet
favicon: null
layout_spectrum: 0.8299881785642356
typography_spectrum: 0.43773130141198635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8512757746502757
  lightness: 0.42596133472397923
  saturation: 0.6052010557614267
  rhythmicContrast: 0.8304099794477224
purpose: []
